# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15a5eeb3ca85e3a0226fc4e0812734e895c0849ee3cea873febaf8a766880f4b89d817886d73b9fbf4f32a3099e57fdca8f5cec303ff0a84006e7c533607a767

test:
  secret_key_base: 9921b353299064012fcbe7450dd6e61fb0ea4baba7102936be72000cc059608a401f3db12198838602320255a58399af611cba8775470d10bba37fb91a7f69e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
